import "./globals.css";
import { Inter } from "next/font/google";
import { HoverContextProvider } from "@/providers/CursorHoverProvider";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Sahil | Portfolio",
    description: "Generated by create next app"
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body className={inter.className}>
              <ToastContainer />
                <HoverContextProvider>{children}</HoverContextProvider>
            </body>
        </html>
    );
}
